print(' ')
print("Welcome to MadLibs!")
print("Please enter 15 funny words below.")
adj1=input("1. Adjective: ")
noun1=input("2. Noun, (Animal or Creature): ")
verb_past1=input("3. Verb, Past Tense: ")
adv1=input("4. Adverb: ")
adj2=input("5. Adjective: ")
noun2=input("6. Noun: ")
peanuts=input("7. Food, plural: ")
color=input("8. Color: ")
noun3=input("9. Noun, (Animal or Creature): ")
adj3=input("10. Adjective: ")
flavor=input("11. Noun: ")
verb1=input("12. Verb: ")
adv2=input("13. Adverb: ")
verb_past2=input("14. Verb, Past Tense: ")
adj4=input("15. Adjective: ")

print(' ')
print("Today, when I went to the zoo, I saw a",adj1,noun1,"jumping up and down in its tree.")
print("It ",adv1," ",verb_past1," ","through the large tunnel that led to its ",adj2," ",noun2,".",sep='')
print("I got some",peanuts,"and passed them through the cage to the gigantic",color,noun3)
print("which was towering above my head. Feeding that",noun3,"made me hungry.")
print("So I went to get a",adj3,"scoop of",flavor,"flavored ice cream. It was delicious and")
print("filled me up. After all that ice cream, I had to",verb1,adv2,"to catch the bus.")
print("When I got home I",verb_past2,"my mom for a",adj4, "day at the zoo.")
print(' ')