print(' ')
print("This is the magic cat! He will bring you good luck!")
print(".∧＿∧")
print("( ･ω･｡)つ━☆・*。")
print("⊂　 ノ 　　　・゜+.")
print("しーＪ　　　°。+ *´¨)")
print("　　　　　　　　　.· ´¸.·*´¨) ¸.·*¨)")
print("　　　　　　　　　　(¸.·´ (¸.·’* ☆")
print(' ')
cont=input("Press Enter to select a new option.")
print(' ')