def display_menu():
    print(' ')
    print("Please select an option:")
    print("Type '1' for area calculator.")
    print("Type '2' for Magic 8 Ball.")
    print("Type '3' for MadLibs.")
    print("Type '4' for The Office Trivia Game.")
    print("Type '5' for Rock, Paper, Scissors.")
    print("Type 'more' for More Options.")
    print(' ')
    print("Or type 'sign off' to sign off.")
    print(' ')

def display_more():
    print(' ')
    print("MORE OPTIONS")
    print("Type any of the following for a surprise:")
    print(' ')
    print('- magic cat')
    print('- doggo')
    print('- love')
    print(' ')
    cont=input("Press Enter to select a new option.")
    print(' ')